"""Add notice and issue columns

Revision ID: c176c6153b09
Revises: 
Create Date: 2025-05-30 16:36:51.040576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c176c6153b09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_data_id'), table_name='store_data')
    op.drop_table('store_data')
    op.alter_column('board_reply', 'text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_board_reply_id'), table_name='board_reply')
    op.drop_index(op.f('ix_excel_data_data_type'), table_name='excel_data')
    op.drop_column('excel_data', 'data_type')
    op.add_column('site_settings', sa.Column('notice', sa.Text(), nullable=True))
    op.add_column('site_settings', sa.Column('issue', sa.Text(), nullable=True))
    op.alter_column('site_settings', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'role')
    op.drop_column('users', 'first_login')
    op.drop_column('users', 'name')
    op.drop_column('users', 'level')
    op.drop_column('users', 'team1')
    op.drop_column('users', 'team2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('team2', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('team1', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('level', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('first_login', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('role', sa.VARCHAR(), nullable=True))
    op.alter_column('site_settings', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('site_settings', 'issue')
    op.drop_column('site_settings', 'notice')
    op.add_column('excel_data', sa.Column('data_type', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_excel_data_data_type'), 'excel_data', ['data_type'], unique=False)
    op.create_index(op.f('ix_board_reply_id'), 'board_reply', ['id'], unique=False)
    op.alter_column('board_reply', 'text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('store_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_data_id'), 'store_data', ['id'], unique=False)
    # ### end Alembic commands ###
